### PR TITLE
fix: don't panic when return is nil

### LINKED ISSUE #8: Exporter crashes on region quota query
# Bug Report

Upon failure when querying region quotas the exporter crashes.

## Expected Behaviour

It should retry using an exponential back-off.

## Actual Behaviour

It crashes completely with `invalid memory address or nil pointer dereference`:

```
time="2020-06-26T12:47:11Z" level=info msg="Starting gcp_quota_exporter (version=, branch=, revision=)" source="main.go:164"
time="2020-06-26T12:47:11Z" level=info msg="Build context (go=go1.13.12, user=, date=)" source="main.go:165"
time="2020-06-26T12:47:16Z" level=info msg="Google Project: XXXXXX" source="main.go:210"
time="2020-06-26T12:47:16Z" level=info msg="Listening on :9592" source="main.go:211"
time="2020-06-26T12:51:09Z" level=error msg="Failure when querying region quotas: Get https://www.googleapis.com/compute/v1/projects/XXXXXX/regions?alt=json&prettyPrint=false: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" source="main.go:73"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0xb1a206]

goroutine 124 [running]:
main.(*Exporter).Collect(0xc0002da090, 0xc00036e120)
	/app/main.go:94 +0xc6
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v0.9.3/prometheus/registry.go:434 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v0.9.3/prometheus/registry.go:526 +0xe12
```

### PR DESCRIPTION
**Pull request by Duologic**
If the scrape fails, the return is nil for either project or regionList.
We should not try to access project.Quotas or regionList.Items in that
case.

Bonus: Even if the regionList call fails, we can still return the
project level results.

fixes #8

### CODE REVIEW

**Comment by Duologic** [comment]
It would be great to fix this here so we don't have to build it on our own fork.

**Review by primeroz — DISMISSED** [review]
@Duologic Looks good to me

File: main.go [hunk 1]
```diff
@@ -71,7 +71,7 @@ func (e *Exporter) scrape() (up float64, prj *compute.Project, rgl *compute.Regi
 	regionList, err := e.service.Regions.List(e.project).Do()
 	if err != nil {
 		log.Errorf("Failure when querying region quotas: %v", err)
-		return 0, nil, nil
+		return 0, project, nil
```
Comment (primeroz) [inline main.go:74]: @Duologic one thing that came up to me after initial approval.

While i like the idea of returning the `project` when that part succeded ... i am not sure we should return `up` as 0 here or as `1` ?

On one side the Regions request failed so it would make sense to return 0 , on the other side though we are returning some data , for the project, so returning up as `0` might be misleading ?

Comment (primeroz) [reply main.go:74]: Ok I will approve and merge as it is.

I think is fair to consider the scrape as unealthy if any of the scrapes fails

**Review by primeroz — APPROVED** [review]

File: main.go (hunk 1 above)
Comment (Duologic) [reply main.go:74]: There is an argument in there that bit-wise doesn't cover the load, a more granular `up`, `partial` and `down` approach would make more sense, but I don't see much benefit in the extra effort.

**Comment by Duologic** [comment]
Thanks!
